[project]
name = "gitlab-mcp-server"
version = "0.2.0"
description = "GitLab MCP (Model Context Protocol) server for interacting with GitLab API through AI Clients"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "mcp[cli]>=1.6.0",
    "pydantic>=2.11.3",
    "pydantic-settings>=2.8.1",
    "asyncio>=3.4.3",
]
authors = [{ name = "Adit pal Singh", email = "aditpalsing@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
keywords = ["gitlab", "mcp", "ai", "server"]

[project.urls]
Homepage = "https://github.com/Adit-999/gitlab-mcp"
Documentation = "https://github.com/Adit-999/gitlab-mcp#readme"

[project.optional-dependencies]
dev = [
    "black>=24.2.0",
    "flake8>=7.0.0",
    "mypy>=1.8.0",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.5",
]
ruff = ["ruff>=0.11.5"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
